//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexDialog {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexDialog.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Globalization;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using RegexDialog;
        /////usings
        ///
        ///public class CSharpReplaceContainer
        ///{
        ///    //global
        ///
        ///    //match
        ///    public string Replace(Match match, int matchIndex, string fileName, int globalIndex, int fileIndex)
        ///    {
        ///        //code
        ///    }
        ///    //endmatch
        ///
        ///    //group
        ///    pu [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CSharpReplaceContainer {
            get {
                return ResourceManager.GetString("CSharpReplaceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Regex&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;CharClass&quot; foreground=&quot;Blue&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;NegativeCharClass&quot; foreground=&quot;OrangeRed&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;Quantifier&quot; foreground=&quot;DarkViolet&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;QuantifierNumber&quot; foreground=&quot;Red&quot; fontWeight=&quot;normal&quot;/&gt;
        ///    &lt;Color name=&quot;CharEscape&quot; foreground=&quot;Gray&quot; fontWeight=&quot;normal&quot;/&gt;
        ///    &lt;Color name=&quot;Comment [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Regex_syntax_color {
            get {
                return ResourceManager.GetString("Regex_syntax_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;Data&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;Character Escapes&quot;,
        ///            &quot;Description&quot;: &quot;Escape characters that signal to the regular expression parser a special char&quot;,
        ///            &quot;Elements&quot;: [
        ///                {
        ///                    &quot;Name&quot;: &quot;Bell &quot;,
        ///                    &quot;Description&quot;: &quot;Matches a bell (alarm) \\u0007.&quot;,
        ///                    &quot;Value&quot;: &quot;\\a&quot;
        ///                },
        ///                {
        ///                    &quot;Name&quot;: &quot;Backspace &quot;,
        ///                    &quot;Description&quot;: &quot;Matches a backspace \\u [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string RegexLanguageElements {
            get {
                return ResourceManager.GetString("RegexLanguageElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Regex&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Substitution&quot; foreground=&quot;Blue&quot; fontWeight=&quot;bold&quot;/&gt;
        ///
        ///    &lt;RuleSet&gt;
        ///        &lt;Rule color=&quot;Substitution&quot;&gt;
        ///            \$([$`&apos;+_&amp;amp;]|\d+(?!\d)|([{]\w*[}]))
        ///        &lt;/Rule&gt;
        ///    &lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;.
        /// </summary>
        internal static string Replace_syntax_color {
            get {
                return ResourceManager.GetString("Replace_syntax_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;Data&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;Value of matched group by group number &quot;,
        ///            &quot;Description&quot;: &quot;Substitutes the last substring matched by group number (decimal).&quot;,
        ///            &quot;Value&quot;: &quot;$number&quot;
        ///        },
        ///        {
        ///            &quot;Name&quot;: &quot;Value of matched group by group name &quot;,
        ///            &quot;Description&quot;: &quot;Substitutes the last substring matched by group name (string).&quot;,
        ///            &quot;Value&quot;:&quot;${name}&quot;
        ///        },
        ///        {
        ///            &quot;Name&quot;: &quot;Dollar sign &quot;,
        ///            &quot;Descrip [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ReplaceLanguageElements {
            get {
                return ResourceManager.GetString("ReplaceLanguageElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   &lt;ItemGroup&gt;
        ///    &lt;Resource Include=&quot;TextSource.txt&quot; /&gt;
        ///  &lt;/ItemGroup&gt;.
        /// </summary>
        internal static string TextSourceAsResourceInCsProj {
            get {
                return ResourceManager.GetString("TextSourceAsResourceInCsProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Globalization;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using RegexDialog;
        /////usings
        ///
        ///public class TextSourceContainer
        ///{
        ///    public object Get()
        ///    {
        ///        //code
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string TextSourceContainer {
            get {
                return ResourceManager.GetString("TextSourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///
        ///namespace projectname
        ///{
        ///    class Program
        ///    {
        ///        private static string pattern = &quot;$pattern$&quot;;
        ///        private static string replacement = &quot;$replacement$&quot;;
        ///        private static RegexOptions options = _options_;
        ///        private static Regex regex = new Regex(pattern, options);
        ///
        ///        private static string input = (new TextSourceContainer()).Get().ToString();
        ///
        ///        static void Main(string[]  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string VSProgram {
            get {
                return ResourceManager.GetString("VSProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
        ///    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///&lt;/Project&gt;
        ///.
        /// </summary>
        internal static string VSProject {
            get {
                return ResourceManager.GetString("VSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Visual Studio Solution File, Format Version 12.00
        ///Project(&quot;{$guid2$}&quot;) = &quot;$projectname$&quot;, &quot;$projectname$\$projectname$.csproj&quot;, &quot;{$guid1$}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///		{$guid1$}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
        ///		{$guid1$}.Debug|Any CPU.Build.0 = Debug|Any CPU
        ///		{$guid1$}.Release|Any [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string VSSolution {
            get {
                return ResourceManager.GetString("VSSolution", resourceCulture);
            }
        }
    }
}
